#include "py_label.hpp"

#include "py_binary_stream.hpp"

#include <boost/python.hpp>
#include <boost/python/detail/wrap_python.hpp>

#include <medusa/label.hpp>

namespace bp = boost::python;

MEDUSA_NAMESPACE_USE

void PydusaLabel(void)
{
  bp::class_<Label>("Label", bp::no_init)
    .add_property("name",  &Label::GetName)
    .add_property("label", &Label::GetLabel)
    .def("__str__",        &Label::GetLabel)
    .def("is_auto_gen",    &Label::IsAutoGenerated)
    ;
}