#include "py_label.hpp"

#include "py_binary_stream.hpp"

#include <boost/python.hpp>
#include <boost/python/detail/wrap_python.hpp>

#include <medusa/label.hpp>

namespace bp = boost::python;

MEDUSA_NAMESPACE_USE

void PydusaLabel(void)
{
  bp::class_<Label>("Label", bp::no_init)
    .add_property("name",  &Label::GetName)
    .add_property("label", &Label::GetLabel)
    .def("__str__",        &Label::GetLabel)
    .def("is_auto_gen",    &Label::IsAutoGenerated)

    .add_property("is_unk",  &Label::IsUnknown)
    .add_property("is_code", &Label::IsCode)
    .add_property("is_func", &Label::IsFunction)
    .add_property("is_data", &Label::IsData)
    .add_property("is_str",  &Label::IsString)
    .add_property("is_imp",  &Label::IsImported)
    .add_property("is_exp",  &Label::IsExported)
    .add_property("is_glb",  &Label::IsGlobal)
    .add_property("is_lcl",  &Label::IsLocal)
    ;
}