#include "pydusa.hpp"

#include <pybind11/pybind11.h>

#include <medusa/label.hpp>

namespace py = pybind11;

MEDUSA_NAMESPACE_USE

void PydusaLabel(py::module& rMod)
{
  py::class_<Label>(rMod, "Label")
    .def_property_readonly("name",  &Label::GetName)
    .def_property_readonly("label", &Label::GetLabel)
    .def("__str__",        &Label::GetLabel)
    .def("is_auto_generated",    &Label::IsAutoGenerated)

    .def_property_readonly("is_unknown",  &Label::IsUnknown)
    .def_property_readonly("is_code", &Label::IsCode)
    .def_property_readonly("is_function", &Label::IsFunction)
    .def_property_readonly("is_data", &Label::IsData)
    .def_property_readonly("is_string",  &Label::IsString)
    .def_property_readonly("is_imported",  &Label::IsImported)
    .def_property_readonly("is_exported",  &Label::IsExported)
    .def_property_readonly("is_global",  &Label::IsGlobal)
    .def_property_readonly("is_local",  &Label::IsLocal)
    ;
}