#!/usr/bin/expect -f

spawn bash cmake-3.2.1-Linux-x86_64.sh --prefix=/usr
expect "More"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
send -- "y\r"
expect "Do you accept the license *:"
send -- "y\r"
interact
